apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: helloapps.apps.example.com
spec:
  group: apps.example.com
  names:
    kind: HelloApp
    plural: helloapps
    singular: helloapp
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                  minimum: 0
                  default: 1
                image:
                  type: string
            status:
              type: object
              properties:
                readyReplicas:
                  type: integer
